// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct HttpClientResponse {
  var statusCode: Int64
  var body: String

  static func fromList(_ list: [Any?]) -> HttpClientResponse? {
    let statusCode = list[0] is Int64 ? list[0] as! Int64 : Int64(list[0] as! Int32)
    let body = list[1] as! String

    return HttpClientResponse(
      statusCode: statusCode,
      body: body
    )
  }
  func toList() -> [Any?] {
    return [
      statusCode,
      body,
    ]
  }
}

private class HttpNativeClientHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return HttpClientResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HttpNativeClientHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HttpClientResponse {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HttpNativeClientHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HttpNativeClientHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HttpNativeClientHostApiCodecWriter(data: data)
  }
}

class HttpNativeClientHostApiCodec: FlutterStandardMessageCodec {
  static let shared = HttpNativeClientHostApiCodec(readerWriter: HttpNativeClientHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HttpNativeClientHostApi {
  func getUrl(url: String, completion: @escaping (Result<HttpClientResponse, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HttpNativeClientHostApiSetup {
  /// The codec used by HttpNativeClientHostApi.
  static var codec: FlutterStandardMessageCodec { HttpNativeClientHostApiCodec.shared }
  /// Sets up an instance of `HttpNativeClientHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HttpNativeClientHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.http_client.HttpNativeClientHostApi.getUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.getUrl(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getUrlChannel.setMessageHandler(nil)
    }
  }
}
